# -*- coding: utf-8 -*-
""".dockerignore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uuqeGadhPfPiZpbiF8xUh9a3jVNpXPnv
"""

__pycache__
*.pyc
*.pyo
*.pyd
*.git
*.idea
.env