# Usamos la imagen oficial de Python 3.11
FROM python:3.11-slim

# Creamos un directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los archivos necesarios
COPY requirements.txt .
COPY app.py .
COPY modelo.pth .   # si tu modelo se llama así
COPY vaca.jpg .      # si quieres un ejemplo incluido

# Instalamos las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponemos el puerto donde correrá Flask
EXPOSE 5000

# Comando para iniciar la app
CMD ["python", "app.py"]
