# -*- coding: utf-8 -*-
"""Procfile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWNRx5K9Onkz_MpqRU3lQDaOcJwrmGSG
"""

with open("Procfile", "w") as f:
    f.write("web: gunicorn app:app")