# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MreeZ81dBSoNTX8XQN5T93_vlodpcnDi
"""

requirements = """
flask
torch
torchvision
timm
pillow
scikit-learn
gunicorn
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)
web: python app.py